version: "3"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      SERVICES: "s3"
      DEFAULT_REGION: "ap-northeast-2"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"