version: "3"

services:
  airflow:
    container_name: airflow
    image: apache/airflow:2.0.1
    depends_on:
      - airflow-postgres
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@airflow-postgres:5432/airflow?sslmode=disable
    command: bash -c "airflow db init || airflow webserver"
    volumes:
      - .:/opt/airflow/dags
  airflow-postgres:
    container_name: airflow-postgresql
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow